// Database types
// This file is normally auto-generated by `pnpm db:types`
// (which runs `supabase gen types typescript --local`).
// Until the local Supabase instance is started, this minimal hand-typed
// shape mirrors the schema in supabase/migrations/* and unblocks compilation.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          display_name: string;
          role: 'leader' | 'operator';
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id: string;
          username: string;
          display_name: string;
          role?: 'leader' | 'operator';
          avatar_url?: string | null;
        };
        Update: Partial<Database['public']['Tables']['profiles']['Insert']> & {
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      resources: {
        Row: {
          id: string;
          code: string;
          label: string;
          kind: 'reactor' | 'filler' | 'mixer' | 'other';
          position: number;
          active: boolean;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          code: string;
          label: string;
          kind?: 'reactor' | 'filler' | 'mixer' | 'other';
          position?: number;
          active?: boolean;
        };
        Update: Partial<Database['public']['Tables']['resources']['Insert']> & {
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      production_orders: {
        Row: {
          id: string;
          order_number: number;
          batch_number: number;
          product_name: string | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          order_number: number;
          batch_number: number;
          product_name?: string | null;
          notes?: string | null;
          created_by?: string | null;
        };
        Update: Partial<Database['public']['Tables']['production_orders']['Insert']> & {
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'production_orders_created_by_fkey'; columns: ['created_by']; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      production_runs: {
        Row: {
          id: string;
          order_id: string;
          resource_id: string;
          status: 'pending' | 'active' | 'completed' | 'cancelled';
          units_produced: number;
          started_at: string | null;
          ended_at: string | null;
          started_by: string | null;
          finished_by: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          order_id: string;
          resource_id: string;
          status?: 'pending' | 'active' | 'completed' | 'cancelled';
          units_produced?: number;
          started_at?: string | null;
          ended_at?: string | null;
          started_by?: string | null;
          finished_by?: string | null;
          created_by?: string | null;
        };
        Update: Partial<Database['public']['Tables']['production_runs']['Insert']> & {
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'production_runs_order_id_fkey'; columns: ['order_id']; referencedRelation: 'production_orders'; referencedColumns: ['id'] },
          { foreignKeyName: 'production_runs_resource_id_fkey'; columns: ['resource_id']; referencedRelation: 'resources'; referencedColumns: ['id'] },
        ];
      };
      operators: {
        Row: {
          id: string;
          full_name: string;
          job_title: string;
          active: boolean;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          full_name: string;
          job_title: string;
          active?: boolean;
        };
        Update: Partial<Database['public']['Tables']['operators']['Insert']> & {
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      attendances: {
        Row: {
          id: string;
          operator_id: string;
          attended_on: string;
          status: 'present' | 'other_sector' | 'medical_leave' | 'absent' | 'holiday';
          note: string | null;
          recorded_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          operator_id: string;
          attended_on: string;
          status: 'present' | 'other_sector' | 'medical_leave' | 'absent' | 'holiday';
          note?: string | null;
          recorded_by?: string | null;
        };
        Update: Partial<Database['public']['Tables']['attendances']['Insert']> & {
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'attendances_operator_id_fkey'; columns: ['operator_id']; referencedRelation: 'operators'; referencedColumns: ['id'] },
        ];
      };
      audit_logs: {
        Row: {
          id: number;
          occurred_at: string;
          actor_id: string | null;
          actor_name: string | null;
          entity: 'production_order' | 'production_run' | 'attendance' | 'operator' | 'resource' | 'profile';
          entity_id: string | null;
          action: 'create' | 'update' | 'delete' | 'start' | 'finish' | 'cancel';
          before: Json | null;
          after: Json | null;
          diff: Json | null;
          context: Json | null;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
    };
    Views: {
      mv_daily_production: {
        Row: {
          production_day: string;
          resource_id: string;
          resource_label: string;
          runs_count: number;
          total_units: number;
          avg_duration_seconds: number;
        };
        Relationships: [];
      };
      mv_resource_ranking: {
        Row: {
          resource_id: string;
          label: string;
          position: number;
          total_units: number;
          completed_runs: number;
          last_completed_at: string | null;
        };
        Relationships: [];
      };
      mv_attendance_summary: {
        Row: {
          attended_on: string;
          status: 'present' | 'other_sector' | 'medical_leave' | 'absent' | 'holiday';
          operators_count: number;
        };
        Relationships: [];
      };
    };
    Functions: {
      is_leader: { Args: Record<string, never>; Returns: boolean };
      current_profile_id: { Args: Record<string, never>; Returns: string };
      refresh_production_mvs: { Args: Record<string, never>; Returns: void };
      refresh_attendance_mvs: { Args: Record<string, never>; Returns: void };
    };
    Enums: {
      user_role: 'leader' | 'operator';
      production_status: 'pending' | 'active' | 'completed' | 'cancelled';
      attendance_status: 'present' | 'other_sector' | 'medical_leave' | 'absent' | 'holiday';
      resource_kind: 'reactor' | 'filler' | 'mixer' | 'other';
      audit_entity: 'production_order' | 'production_run' | 'attendance' | 'operator' | 'resource' | 'profile';
      audit_action: 'create' | 'update' | 'delete' | 'start' | 'finish' | 'cancel';
    };
  };
}

// Convenience aliases
export type Profile = Database['public']['Tables']['profiles']['Row'];
export type Resource = Database['public']['Tables']['resources']['Row'];
export type ProductionOrder = Database['public']['Tables']['production_orders']['Row'];
export type ProductionRun = Database['public']['Tables']['production_runs']['Row'];
export type Operator = Database['public']['Tables']['operators']['Row'];
export type Attendance = Database['public']['Tables']['attendances']['Row'];
export type AuditLog = Database['public']['Tables']['audit_logs']['Row'];
export type DailyProductionRow = Database['public']['Views']['mv_daily_production']['Row'];
export type ResourceRankingRow = Database['public']['Views']['mv_resource_ranking']['Row'];
export type AttendanceSummaryRow = Database['public']['Views']['mv_attendance_summary']['Row'];
